#!/usr/bin/env bash
# install nginx web server on server and start it

sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
